const PDFDocument = require('pdfkit');
const path = require('path');

function generateItemPDF(item) {
    const doc = new PDFDocument({ size: 'A4', margin: 0 });

    const pageWidth = doc.page.width;
    const margin = 50;
    const contentWidth = pageWidth - margin * 2;

    // Colors (matching your site's --lf- variables)
    const navy = '#0f172a';
    const blue = '#2563eb';
    const slate = '#64748b';
    const border = '#e2e8f0';
    const bg = '#f8fafc';

    const typeColor = item.type === 'Lost' ? '#dc2626' : '#16a34a';

    // ---------- Header banner ----------
    doc.rect(0, 0, pageWidth, 130).fill(navy);

    doc
        .fillColor('#ffffff')
        .fontSize(11)
        .font('Helvetica-Bold')
        .text('CAMPUS LOST & FOUND', margin, 35, { characterSpacing: 1 });

    doc
        .fillColor('#ffffff')
        .fontSize(26)
        .font('Helvetica-Bold')
        .text(item.title, margin, 58, { width: contentWidth - 120 });

    // Type badge, top-right of header
    const badgeText = item.type.toUpperCase();
    const badgeWidth = doc.widthOfString(badgeText, { font: 'Helvetica-Bold', size: 10 }) + 24;
    const badgeX = pageWidth - margin - badgeWidth;
    doc.roundedRect(badgeX, 38, badgeWidth, 24, 12).fill(typeColor);
    doc
        .fillColor('#ffffff')
        .fontSize(10)
        .font('Helvetica-Bold')
        .text(badgeText, badgeX, 45, { width: badgeWidth, align: 'center' });

    let y = 155;

    // ---------- Image ----------
    if (item.image) {
        try {
            const imagePath = path.join(__dirname, '..', 'public', item.image);
            const imgHeight = 220;

            doc.save();
            doc.roundedRect(margin, y, contentWidth, imgHeight, 8).clip();
            doc.image(imagePath, margin, y, { width: contentWidth, height: imgHeight });
            doc.restore();

            doc.roundedRect(margin, y, contentWidth, imgHeight, 8).stroke(border);
            y += imgHeight + 25;
        } catch (imgError) {
            console.log('Could not embed image in PDF:', imgError.message);
        }
    }

    // ---------- Info card (2-column grid) ----------
    const cardPadding = 20;
    const rowHeight = 42;
    const rows = [
        ['Category', item.category],
        ['Location', item.location],
        ['Date', item.date.toDateString()],
    ];
    if (item.owner) rows.push(['Posted by', item.owner.username]);

    const cardHeight = rowHeight * rows.length + cardPadding * 2;

    doc.roundedRect(margin, y, contentWidth, cardHeight, 10).fill(bg).stroke(border);

    let rowY = y + cardPadding;
    rows.forEach(([label, value], i) => {
        doc
            .fillColor(slate)
            .font('Helvetica-Bold')
            .fontSize(9)
            .text(label.toUpperCase(), margin + cardPadding, rowY, { characterSpacing: 0.5 });

        doc
            .fillColor(navy)
            .font('Helvetica')
            .fontSize(13)
            .text(value, margin + cardPadding, rowY + 13);

        if (i < rows.length - 1) {
            doc
                .moveTo(margin + cardPadding, rowY + rowHeight - 8)
                .lineTo(pageWidth - margin - cardPadding, rowY + rowHeight - 8)
                .strokeColor(border)
                .stroke();
        }

        rowY += rowHeight;
    });

    y += cardHeight + 30;

    // ---------- Description ----------
    doc
        .fillColor(navy)
        .font('Helvetica-Bold')
        .fontSize(14)
        .text('Description', margin, y);

    doc
        .moveTo(margin, y + 20)
        .lineTo(margin + 40, y + 20)
        .lineWidth(3)
        .strokeColor(blue)
        .stroke();

    doc
        .fillColor('#334155')
        .font('Helvetica')
        .fontSize(11.5)
        .text(item.description, margin, y + 32, {
            width: contentWidth,
            align: 'justify',
            lineGap: 4,
        });

    // ---------- Footer ----------
    const footerY = doc.page.height - 60;
    doc
        .moveTo(margin, footerY)
        .lineTo(pageWidth - margin, footerY)
        .strokeColor(border)
        .stroke();

    doc
        .fillColor(slate)
        .font('Helvetica')
        .fontSize(8.5)
        .text(
            `Generated by Campus Lost & Found · ${new Date().toLocaleString()}`,
            margin,
            footerY + 12,
            { width: contentWidth, align: 'center' }
        );

    return doc;
}

module.exports = generateItemPDF;